# Generated by Django 6.0.5 on 2026-05-20 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='telefon number soralgan fromatda bolsihi kerka ', regex='^\\+9989\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('manager', 'Manager'), ('consignor', 'Consignor')], default='Driver', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='telefon number soralgan fromatda bolsihi kerka ', regex='^\\+9989\\d{9}$')]),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='telefon number soralgan fromatda bolsihi kerka ', regex='^\\+9989\\d{9}$')])),
                ('code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
