# Generated by Django 6.0.5 on 2026-05-20 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_driver_created_at_remove_driver_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='telefon number soralgan fromatda bolsihi kerka ', regex='^\\+9989\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='telefon number soralgan fromatda bolsihi kerka ', regex='^\\+9989\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('manager', 'Manager'), ('consignor', 'Consignor')], default='driver', max_length=20),
        ),
    ]
