# Generated by Django 6.0.5 on 2026-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driver_phone_number_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cenceled_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
