# Generated by Django 6.0.5 on 2026-05-20 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cenceled_offer_user_learned_user_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('summa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('initial_borrow', models.BooleanField(blank=True, default=0, null=True)),
                ('leter_on_borrow', models.BooleanField(blank=True, default=0, null=True)),
                ('note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
