# Generated by Django 6.0.5 on 2026-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_driver_user_alter_manager_user_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('manager', 'Manager'), ('consignor', 'Consignor'), ('dispecher', 'dispecher'), ('yuk tashuvchi firma', 'Yuk tashuvchi firma')], default='driver', max_length=20),
        ),
    ]
