# Generated by Django 6.0.5 on 2026-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzbek', models.CharField(max_length=200)),
                ('russian', models.CharField(max_length=200)),
                ('krilcha', models.CharField(max_length=200)),
                ('kod', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=0)),
                ('volume_inputi', models.FloatField(blank=True, choices=[('no', 'NO'), ('yes', 'Yes')], default="yo'/q", max_length=20, null=True)),
                ('board_type_inputi', models.FloatField(blank=True, choices=[('no', 'NO'), ('yes', 'Yes')], default="yo'/q", max_length=20, null=True)),
                ('temperature_inputi', models.FloatField(blank=True, choices=[('no', 'NO'), ('yes', 'Yes')], default="yo'/q", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
