# Generated by Django 6.0.5 on 2026-05-21 08:04

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_driver_user_alter_manager_user_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', django_countries.fields.CountryField(max_length=2)),
                ('to_country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.CharField(choices=[('ad', 'Ad'), ('inprocess', 'Inprocess'), ('delivered', 'Delivered'), ('unapplied', 'Unapplied')], default='ad', max_length=100)),
                ('load', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driverlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('on_road', 'On_road')], default='empty', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driverlocation', to='users.driver')),
            ],
        ),
    ]
