# Generated by Django 6.0.5 on 2026-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('currency', 'Currency'), ('document', 'Document'), ('body', 'Body'), ('unit', 'Unit'), ('carrier', 'Carrier'), ('cargo_status', 'Cargo Status'), ('offer_status', 'Offer Status'), ('payment', 'Payment'), ('partial_load', 'Partial Load'), ('user_type', 'User Type'), ('truck_type', 'Truck Type')], default='currency', max_length=20)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('name_curl', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=120, null=True)),
                ('symbol', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
    ]
